'use client'

import { useState } from 'react'
import { ArrowDown, ArrowUpRight, Building2, Check, ChevronDown, Compass, House, Camera, Mail, Menu, MessageCircle, Search, X } from 'lucide-react'
import { COMPANY, PROPERTY_LINKS } from '@/lib/links'

const navByLang = {
  ES: [['Vivienda', 'properties'], ['Barcelona', 'barcelona'], ['Madrid', 'madrid'], ['Servicios', 'services'], ['Reubicación', 'relocation'], ['Nosotros', 'about'], ['Contacto', 'contact']],
  CA: [['Habitatge', 'properties'], ['Barcelona', 'barcelona'], ['Madrid', 'madrid'], ['Serveis', 'services'], ['Reubicació', 'relocation'], ['Nosaltres', 'about'], ['Contacte', 'contact']],
  EN: [['Housing', 'properties'], ['Barcelona', 'barcelona'], ['Madrid', 'madrid'], ['Services', 'services'], ['Relocation', 'relocation'], ['About us', 'about'], ['Contact', 'contact']],
  FR: [['Logement', 'properties'], ['Barcelona', 'barcelona'], ['Madrid', 'madrid'], ['Services', 'services'], ['Relocation', 'relocation'], ['À propos', 'about'], ['Contact', 'contact']],
} as const
const copy = {
  ES: { home: 'Encuentra tu', next: 'próximo hogar.', hero: 'Somos una empresa de relocation para clientes nacionales e internacionales que buscan trasladarse a Barcelona o Madrid. Te ayudamos a encontrar vivienda de forma más personal, más precisa, más tuya.', rent: 'Ver pisos en alquiler', sale: 'Ver opciones de vivienda', markets: 'Nuestros mercados', cities: 'Dos ciudades.', reality: 'Una nueva realidad.', properties: 'Selección privada', housing: 'Tu nueva', housingEm: 'vivienda', services: 'Cómo trabajamos', servicesTitle: 'Un servicio a la', servicesEm: 'altura de tu búsqueda.', relocation: 'Reubicación', relocationTitle: 'Mucho más que', relocationEm: 'encontrar un hogar.', relocationText: 'Nuestro servicio de relocation está diseñado para clientes que necesitan apoyo antes, durante y después de trasladarse. Te acompañamos en la búsqueda, selección y coordinación de tu llegada y nueva vivienda en Barcelona y Madrid.', about: 'Sobre nosotros', aboutTitle: 'Te ayudamos a', aboutEm: 'crear tu nueva realidad.', aboutText: 'Somos una empresa de relocation, no una agencia inmobiliaria. Acompañamos a clientes nacionales e internacionales que se trasladan a Barcelona y Madrid.', contact: 'Hablemos', contactTitle: 'Tu próxima dirección', contactEm: 'empieza aquí.', contactText: 'Cuéntanos qué estás buscando y te ayudaremos a encontrarlo.', explore: 'Explora', housingNav: 'Vivienda', relocationFoot: 'Relocation y acompañamiento personalizado' },
  CA: { home: 'Troba la teva', next: 'propera llar.', hero: 'Som una empresa de relocation per a clients nacionals i internacionals que es traslladen a Barcelona o Madrid. T’ajudem a trobar habitatge d’una manera més personal i precisa.', rent: 'Veure lloguers', sale: 'Veure opcions d’habitatge', markets: 'Els nostres mercats', cities: 'Dues ciutats.', reality: 'Una nova realitat.', properties: 'Selecció privada', housing: 'La teva nova', housingEm: 'llar', services: 'Com treballem', servicesTitle: 'Un servei a l’', servicesEm: 'altura de la teva cerca.', relocation: 'Reubicació', relocationTitle: 'Molt més que', relocationEm: 'trobar una llar.', relocationText: 'El nostre servei de relocation està pensat per a clients que necessiten suport abans, durant i després del trasllat. T’acompanyem en la cerca, selecció i coordinació de la teva arribada i nova llar a Barcelona i Madrid.', about: 'Sobre nosaltres', aboutTitle: 'T’ajudem a', aboutEm: 'crear la teva nova realitat.', aboutText: 'Som una empresa de relocation, no una agència immobiliària. Acompanyem clients nacionals i internacionals que es traslladen a Barcelona i Madrid.', contact: 'Parlem', contactTitle: 'La teva propera adreça', contactEm: 'comença aquí.', contactText: 'Explica’ns què busques i t’ajudarem a trobar-ho.', explore: 'Explora', housingNav: 'Habitatge', relocationFoot: 'Relocation i acompanyament personalitzat' },
  EN: { home: 'Find your', next: 'next home.', hero: 'We are a relocation company for national and international clients moving to Barcelona or Madrid. We help you find a home with a more personal and precise approach.', rent: 'View rentals', sale: 'View housing options', markets: 'Our markets', cities: 'Two cities.', reality: 'A new reality.', properties: 'Private selection', housing: 'Your new', housingEm: 'home', services: 'How we work', servicesTitle: 'A service at the', servicesEm: 'height of your search.', relocation: 'Relocation', relocationTitle: 'Much more than', relocationEm: 'finding a home.', relocationText: 'Our relocation service is designed for clients who need support before, during and after their move. We guide you through the search, selection and coordination of your arrival and new home in Barcelona and Madrid.', about: 'About us', aboutTitle: 'We help you', aboutEm: 'create your new reality.', aboutText: 'We are a relocation company, not a real estate agency. We support national and international clients moving to Barcelona and Madrid.', contact: 'Let’s talk', contactTitle: 'Your next address', contactEm: 'starts here.', contactText: 'Tell us what you are looking for and we will help you find it.', explore: 'Explore', housingNav: 'Housing', relocationFoot: 'Relocation and personal support' },
  FR: { home: 'Trouvez votre', next: 'prochain chez-vous.', hero: 'Nous sommes une entreprise de relocation pour les clients nationaux et internationaux qui s’installent à Barcelone ou Madrid. Nous vous aidons à trouver un logement avec un accompagnement personnel et précis.', rent: 'Voir les locations', sale: 'Voir les logements', markets: 'Nos marchés', cities: 'Deux villes.', reality: 'Une nouvelle réalité.', properties: 'Sélection privée', housing: 'Votre nouveau', housingEm: 'chez-vous', services: 'Notre méthode', servicesTitle: 'Un service à la', servicesEm: 'hauteur de votre recherche.', relocation: 'Relocation', relocationTitle: 'Bien plus que', relocationEm: 'trouver un chez-soi.', relocationText: 'Notre service de relocation est conçu pour les clients qui ont besoin de soutien avant, pendant et après leur installation. Nous vous accompagnons dans la recherche, la sélection et la coordination de votre arrivée et de votre nouveau logement à Barcelone et Madrid.', about: 'À propos de nous', aboutTitle: 'Nous vous aidons à', aboutEm: 'créer votre nouvelle réalité.', aboutText: 'Nous sommes une entreprise de relocation, pas une agence immobilière. Nous accompagnons les clients nationaux et internationaux qui s’installent à Barcelone et Madrid.', contact: 'Parlons-en', contactTitle: 'Votre prochaine adresse', contactEm: 'commence ici.', contactText: 'Dites-nous ce que vous recherchez et nous vous aiderons à le trouver.', explore: 'Explorer', housingNav: 'Logement', relocationFoot: 'Relocation et accompagnement personnalisé' },
} as const
const ui = {
  ES: { discover: 'Descubrir mercado', rent: 'Ver alquileres', options: 'Ver opciones de vivienda', inspired: 'La ciudad que inspira.', place: 'Tu lugar en Madrid.', search: 'Búsqueda personalizada', searchText: 'Seleccionamos viviendas según tus necesidades, presupuesto, ubicación y estilo de vida.', rentService: 'Acompañamiento para alquiler', rentText: 'Te ayudamos a encontrar y gestionar tu vivienda de alquiler en Barcelona y Madrid.', buyService: 'Acompañamiento para compra', buyText: 'Te acompañamos en la búsqueda y coordinación de tu vivienda en Barcelona y Madrid.', move: 'Servicio integral para clientes nacionales e internacionales que se trasladan.', before: 'Antes de llegar', during: 'Durante el traslado', after: 'En tu nueva ciudad', write: 'Escríbenos', explore: 'Explora', housing: 'Vivienda', privacy: 'Tu privacidad importa', cookies: 'Usamos solo cookies necesarias para que el sitio funcione correctamente.' },
  CA: { discover: 'Descobrir mercat', rent: 'Veure lloguers', options: 'Veure opcions d’habitatge', inspired: 'La ciutat que inspira.', place: 'El teu lloc a Madrid.', search: 'Cerca personalitzada', searchText: 'Seleccionem habitatges segons les teves necessitats, pressupost, ubicació i estil de vida.', rentService: 'Acompanyament per llogar', rentText: 'T’ajudem a trobar i gestionar el teu habitatge de lloguer a Barcelona i Madrid.', buyService: 'Acompanyament per comprar', buyText: 'T’acompanyem en la cerca i coordinació del teu habitatge a Barcelona i Madrid.', move: 'Servei integral per a clients nacionals i internacionals que es traslladen.', before: 'Abans d’arribar', during: 'Durant el trasllat', after: 'A la teva nova ciutat', write: 'Escriu-nos', explore: 'Explora', housing: 'Habitatge', privacy: 'La teva privacitat importa', cookies: 'Només utilitzem les galetes necessàries perquè el lloc funcioni correctament.' },
  EN: { discover: 'Explore market', rent: 'View rentals', options: 'View housing options', inspired: 'The city that inspires.', place: 'Your place in Madrid.', search: 'Personalised search', searchText: 'We select homes according to your needs, budget, location and lifestyle.', rentService: 'Rental support', rentText: 'We help you find and manage your rental home in Barcelona and Madrid.', buyService: 'Purchase support', buyText: 'We guide you through the search and coordination of your home in Barcelona and Madrid.', move: 'Full support for national and international clients moving to the city.', before: 'Before you arrive', during: 'During the move', after: 'In your new city', write: 'Write to us', explore: 'Explore', housing: 'Housing', privacy: 'Your privacy matters', cookies: 'We only use necessary cookies so the site works correctly.' },
  FR: { discover: 'Découvrir le marché', rent: 'Voir les locations', options: 'Voir les logements', inspired: 'La ville qui inspire.', place: 'Votre place à Madrid.', search: 'Recherche personnalisée', searchText: 'Nous sélectionnons des logements selon vos besoins, votre budget, votre emplacement et votre style de vie.', rentService: 'Accompagnement locatif', rentText: 'Nous vous aidons à trouver et gérer votre logement à Barcelone et Madrid.', buyService: 'Accompagnement à l’achat', buyText: 'Nous vous accompagnons dans la recherche et la coordination de votre logement.', move: 'Un service complet pour les clients nationaux et internationaux qui s’installent.', before: 'Avant votre arrivée', during: 'Pendant l’installation', after: 'Dans votre nouvelle ville', write: 'Écrivez-nous', explore: 'Explorer', housing: 'Logement', privacy: 'Votre vie privée compte', cookies: 'Nous utilisons uniquement les cookies nécessaires au bon fonctionnement du site.' },
} as const
const cardCopy = {
  ES: { barcelonaRent: ['Barcelona / Alquiler', 'Vive Barcelona', 'Viviendas con luz, diseño y ubicación privilegiada.'], barcelonaBuy: ['Barcelona / Compra', 'Compra con visión', 'Espacios para construir tu próxima etapa.'], madridRent: ['Madrid / Alquiler', 'Tu Madrid', 'Viviendas seleccionadas para vivir la ciudad.'], madridBuy: ['Madrid / Compra', 'Una inversión personal', 'Encuentra un espacio que crece contigo.'], select: 'Ver selección', consult: 'Consultar selección', barcelonaIntro: 'Te acompañamos en tu llegada a una de las ciudades más dinámicas y atractivas de Europa.', barcelonaAreas: 'Trabajamos con viviendas en Eixample, Sarrià-Sant Gervasi, Gràcia, Les Corts, Poblenou, Ciutat Vella y otras áreas seleccionadas.', madridIntro: 'Acompañamiento para clientes nacionales e internacionales que buscan vivienda en Madrid.', madridAreas: 'Ofrecemos búsqueda personalizada, selección de vivienda y acompañamiento durante todo el proceso.' },
  CA: { barcelonaRent: ['Barcelona / Lloguer', 'Viu Barcelona', 'Habitatges amb llum, disseny i una ubicació privilegiada.'], barcelonaBuy: ['Barcelona / Compra', 'Compra amb visió', 'Espais per construir la teva propera etapa.'], madridRent: ['Madrid / Lloguer', 'El teu Madrid', 'Habitatges seleccionats per viure la ciutat.'], madridBuy: ['Madrid / Compra', 'Una inversió personal', 'Troba un espai que creix amb tu.'], select: 'Veure selecció', consult: 'Consultar selecció', barcelonaIntro: 'T’acompanyem en la teva arribada a una de les ciutats més dinàmiques i atractives d’Europa.', barcelonaAreas: 'Treballem amb habitatges a Eixample, Sarrià-Sant Gervasi, Gràcia, Les Corts, Poblenou, Ciutat Vella i altres àrees seleccionades.', madridIntro: 'Acompanyament per a clients nacionals i internacionals que busquen habitatge a Madrid.', madridAreas: 'Oferim cerca personalitzada, selecció d’habitatge i acompanyament durant tot el procés.' },
  EN: { barcelonaRent: ['Barcelona / Rental', 'Live Barcelona', 'Homes with light, design and a privileged location.'], barcelonaBuy: ['Barcelona / Purchase', 'Buy with vision', 'Spaces to build your next chapter.'], madridRent: ['Madrid / Rental', 'Your Madrid', 'Selected homes for experiencing the city.'], madridBuy: ['Madrid / Purchase', 'A personal investment', 'Find a space that grows with you.'], select: 'View selection', consult: 'Ask about selection', barcelonaIntro: 'We support your arrival in one of Europe’s most dynamic and attractive cities.', barcelonaAreas: 'We work with homes in Eixample, Sarrià-Sant Gervasi, Gràcia, Les Corts, Poblenou, Ciutat Vella and other selected areas.', madridIntro: 'Support for national and international clients looking for a home in Madrid.', madridAreas: 'We offer a personalised search, home selection and support throughout the process.' },
  FR: { barcelonaRent: ['Barcelone / Location', 'Vivre Barcelone', 'Des logements lumineux, design et idéalement situés.'], barcelonaBuy: ['Barcelone / Achat', 'Acheter avec vision', 'Des espaces pour construire votre prochaine étape.'], madridRent: ['Madrid / Location', 'Votre Madrid', 'Des logements sélectionnés pour vivre la ville.'], madridBuy: ['Madrid / Achat', 'Un investissement personnel', 'Trouvez un espace qui grandit avec vous.'], select: 'Voir la sélection', consult: 'Demander la sélection', barcelonaIntro: 'Nous vous accompagnons dans votre arrivée dans l’une des villes les plus dynamiques d’Europe.', barcelonaAreas: 'Nous travaillons avec des logements à Eixample, Sarrià-Sant Gervasi, Gràcia, Les Corts, Poblenou, Ciutat Vella et d’autres quartiers sélectionnés.', madridIntro: 'Accompagnement pour les clients nationaux et internationaux à la recherche d’un logement à Madrid.', madridAreas: 'Nous proposons une recherche personnalisée, une sélection de logements et un accompagnement tout au long du processus.' },
} as const
const images = {
  hero: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=2200&q=85',
  barcelona: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=1400&q=85',
  madrid: 'https://images.unsplash.com/photo-1543783207-ec64e4d95325?auto=format&fit=crop&w=1400&q=85',
  interior: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1600&q=85',
  relocation: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1600&q=85',
}

function ExternalLink({ href, children, inverse = false }: { href: string; children: React.ReactNode; inverse?: boolean }) {
  return <a href={href} target="_blank" rel="noopener noreferrer" className={`button ${inverse ? 'button-inverse' : ''}`}>{children}<ArrowUpRight size={16} /></a>
}

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [lang, setLang] = useState('ES')
  const [languageOpen, setLanguageOpen] = useState(false)
  const [cookies, setCookies] = useState(true)
  const activeCopy = copy[lang as keyof typeof copy]
  const activeUi = ui[lang as keyof typeof ui]
  const activeCards = cardCopy[lang as keyof typeof cardCopy]
  const nav = navByLang[lang as keyof typeof navByLang]
  const scrollTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false) }

  return (
    <main>
      <header className="site-header">
        <button className="logo" onClick={() => scrollTo('top')} aria-label="Coconut Luxury Flats, inicio">
          COCONUT LUXURY FLATS
        </button>
        <nav className="desktop-nav" aria-label="Navegación principal">
          {nav.map(([label, id]) => <button key={id} onClick={() => scrollTo(id)}>{label}</button>)}
        </nav>
        <div className="header-actions">
          <div className="language"><button className="language-trigger" onClick={() => setLanguageOpen((open) => !open)} aria-label="Cambiar idioma" aria-expanded={languageOpen}><span>{lang}</span><ChevronDown size={13} /></button>
            {languageOpen && <div className="language-menu">{['ES', 'CA', 'EN', 'FR'].map((item) => <button key={item} onClick={() => { setLang(item); setLanguageOpen(false) }} className={lang === item ? 'active' : ''}>{item}</button>)}</div>}
          </div>
          <button className="header-cta" onClick={() => scrollTo('properties')}>{activeCopy.sale} <ArrowUpRight size={14} /></button>
          <button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Cerrar menú' : 'Abrir menú'} aria-expanded={menuOpen}>{menuOpen ? <X /> : <Menu />}</button>
        </div>
      </header>

      {menuOpen && <div className="mobile-menu"><div className="mobile-links">{nav.map(([label, id]) => <button key={id} onClick={() => scrollTo(id)}>{label}<ArrowUpRight size={16} /></button>)}</div><div className="mobile-menu-actions"><ExternalLink href={PROPERTY_LINKS.barcelona.rent}>{activeUi.rent}</ExternalLink><ExternalLink href={PROPERTY_LINKS.barcelona.sale} inverse>{activeUi.options}</ExternalLink></div><div className="mobile-languages">{['ES', 'CA', 'EN', 'FR'].map((item) => <button key={item} onClick={() => setLang(item)} className={lang === item ? 'active' : ''}>{item}</button>)}</div></div>}

      <section className="hero" id="top" style={{ backgroundImage: `linear-gradient(90deg, rgba(12,34,29,.86) 0%, rgba(12,34,29,.54) 52%, rgba(12,34,29,.18) 100%), url(${images.hero})` }}>
        <div className="hero-content"><p className="eyebrow">COCONUT LUXURY FLATS <span>—</span> BARCELONA · MADRID</p><h1>{activeCopy.home}<br /><em>{activeCopy.next}</em></h1><p className="hero-copy">{activeCopy.hero}</p><div className="hero-actions"><ExternalLink href={PROPERTY_LINKS.barcelona.rent}>{activeCopy.rent}</ExternalLink><ExternalLink href={PROPERTY_LINKS.barcelona.sale} inverse>{activeCopy.sale}</ExternalLink></div></div>
        <div className="hero-foot"><span>01 / 04</span><span className="line" /><span>{activeCopy.relocationFoot}</span><button onClick={() => scrollTo('properties')} aria-label="Descubrir más"><ArrowDown size={18} /></button></div>
      </section>

      <section className="intro section-pad"><div className="section-kicker">01 — {activeCopy.markets}</div><div className="intro-grid"><h2>{activeCopy.cities}<br /><em>{activeCopy.reality}</em></h2><p>{activeCopy.hero}</p></div><div className="market-grid" id="markets"><article className="market-card" style={{ backgroundImage: `linear-gradient(0deg, rgba(13,40,33,.88), transparent 75%), url(${images.barcelona})` }}><div><span>01 / Barcelona</span><h3>Barcelona</h3><p>Arquitectura, mar y vida mediterránea.</p><button onClick={() => scrollTo('barcelona')}>{activeUi.discover} <ArrowUpRight size={16} /></button></div></article><article className="market-card" style={{ backgroundImage: `linear-gradient(0deg, rgba(13,40,33,.88), transparent 75%), url(${images.madrid})` }}><div><span>02 / Madrid</span><h3>Madrid</h3><p>Carácter, cultura y una energía única.</p><button onClick={() => scrollTo('madrid')}>{activeUi.discover} <ArrowUpRight size={16} /></button></div></article></div></section>

      <section className="properties section-pad" id="properties"><div className="section-heading"><div><div className="section-kicker">02 — {activeCopy.properties}</div><h2>{activeCopy.housing} <em>{activeCopy.housingEm}</em></h2></div><p>{activeCopy.contactText}</p></div><div className="property-grid"><PropertyCard data={activeCards.barcelonaRent} href={PROPERTY_LINKS.barcelona.rent} image={images.interior} select={activeCards.select} /><PropertyCard data={activeCards.barcelonaBuy} href={PROPERTY_LINKS.barcelona.sale} image={images.barcelona} select={activeCards.select} /><PropertyCard data={activeCards.madridRent} image={images.madrid} select={activeCards.consult} /><PropertyCard data={activeCards.madridBuy} image={images.hero} select={activeCards.consult} /></div></section>

      <section className="city-feature" id="barcelona"><div className="city-image" style={{ backgroundImage: `url(${images.barcelona})` }} /><div className="city-copy"><div className="section-kicker">03 — Barcelona</div><h2>{activeUi.inspired}</h2><p>{activeCards.barcelonaIntro}</p><p className="muted">{activeCards.barcelonaAreas}</p><div className="button-row"><ExternalLink href={PROPERTY_LINKS.barcelona.rent}>{activeUi.rent}</ExternalLink><ExternalLink href={PROPERTY_LINKS.barcelona.sale} inverse>{activeUi.options}</ExternalLink></div></div></section>

      <section className="city-feature reverse" id="madrid"><div className="city-image" style={{ backgroundImage: `url(${images.madrid})` }} /><div className="city-copy"><div className="section-kicker">04 — Madrid</div><h2>{activeUi.place}</h2><p>{activeCards.madridIntro}</p><p className="muted">{activeCards.madridAreas}</p><button className="text-link" onClick={() => scrollTo('contact')}>{activeUi.options} <ArrowUpRight size={17} /></button></div></section>

      <section className="services section-pad" id="services"><div className="section-kicker">05 — {activeCopy.services}</div><div className="services-head"><h2>{activeCopy.servicesTitle}<br /><em>{activeCopy.servicesEm}</em></h2><p>{lang === 'ES' ? 'Experiencia, criterio y una atención que empieza mucho antes de abrir una puerta.' : lang === 'CA' ? 'Experiència, criteri i una atenció que comença molt abans d’obrir una porta.' : lang === 'EN' ? 'Experience, judgement and support that begins long before opening a door.' : 'Expérience, discernement et attention qui commencent bien avant d’ouvrir une porte.'}</p></div><div className="service-grid"><Service icon={<Search />} title={activeUi.search} text={activeUi.searchText} /><Service icon={<House />} title={activeUi.rentService} text={activeUi.rentText} /><Service icon={<Building2 />} title={activeUi.buyService} text={activeUi.buyText} /><Service icon={<Compass />} title={activeCopy.relocation} text={activeUi.move} /></div></section>

      <section className="relocation" id="relocation"><div className="relocation-inner"><div className="relocation-image" style={{ backgroundImage: `linear-gradient(180deg, rgba(16,46,39,.08), rgba(16,46,39,.72)), url(${images.relocation})` }} role="img" aria-label="Acompañamiento personalizado para una nueva llegada" /><div className="relocation-copy"><div className="section-kicker">06 — {activeCopy.relocation}</div><h2>{activeCopy.relocationTitle}<br /><em>{activeCopy.relocationEm}</em></h2><p>{activeCopy.relocationText}</p><div className="relocation-points"><span><b>01</b> {activeUi.before}</span><span><b>02</b> {activeUi.during}</span><span><b>03</b> {activeUi.after}</span></div><button className="text-link light" onClick={() => scrollTo('contact')}>{activeCopy.contact} <ArrowUpRight size={17} /></button></div></div></section>

      <section className="about section-pad" id="about"><div className="about-image" style={{ backgroundImage: `url(${images.interior})` }} /><div className="about-copy"><div className="section-kicker">07 — {activeCopy.about}</div><h2>{activeCopy.aboutTitle}<br /><em>{activeCopy.aboutEm}</em></h2><p>{activeCopy.aboutText}</p><p className="muted">{lang === 'ES' ? 'Trabajamos con clientes nacionales e internacionales y ofrecemos un servicio cercano, ágil y personalizado.' : lang === 'CA' ? 'Treballem amb clients nacionals i internacionals i oferim un servei proper, àgil i personalitzat.' : lang === 'EN' ? 'We work with national and international clients and offer a close, agile and personalised service.' : 'Nous travaillons avec des clients nationaux et internationaux et offrons un service proche, agile et personnalisé.'}</p><div className="signature">Coconut Luxury Flats <span>Barcelona · Madrid</span></div></div></section>

      <section className="contact section-pad" id="contact"><div><div className="section-kicker">08 — {activeCopy.contact}</div><h2>{activeCopy.contactTitle}<br /><em>{activeCopy.contactEm}</em></h2></div><div className="contact-info"><p>{activeCopy.contactText}</p><address>{COMPANY.name}<br />Rambla Catalunya 125<br />08008 Barcelona, España</address><div className="contact-actions"><a className="text-link" href={`mailto:${COMPANY.email}`}>{activeUi.write} <Mail size={17} /></a><a className="text-link" href={COMPANY.whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp <MessageCircle size={17} /></a></div></div></section>

      <footer><div className="footer-brand"><strong>COCONUT LUXURY FLATS</strong><p>Barcelona · Madrid</p><div className="social-links"><a href={COMPANY.instagram} target="_blank" rel="noopener noreferrer" aria-label="Instagram"><Camera size={18} /></a><a href={COMPANY.whatsapp} target="_blank" rel="noopener noreferrer" aria-label="WhatsApp"><MessageCircle size={18} /></a><a href={`mailto:${COMPANY.email}`} aria-label="Email"><Mail size={18} /></a></div></div><div className="footer-links"><div><span>{activeUi.explore}</span>{nav.slice(0, 5).map(([label, id]) => <button key={id} onClick={() => scrollTo(id)}>{label}</button>)}</div><div><span>{activeUi.housing}</span><a href={PROPERTY_LINKS.barcelona.rent} target="_blank" rel="noopener noreferrer">{activeCards.barcelonaRent[0]}</a><a href={PROPERTY_LINKS.barcelona.sale} target="_blank" rel="noopener noreferrer">{activeCards.barcelonaBuy[0]}</a><button onClick={() => scrollTo('madrid')}>{activeCards.madridRent[0]}</button><button onClick={() => scrollTo('madrid')}>{activeCards.madridBuy[0]}</button></div></div><div className="footer-bottom"><span>© 2026 Coconut Luxury Flats</span><span>{activeCopy.relocationFoot}</span></div></footer>

      <div className="mobile-sticky"><a href={PROPERTY_LINKS.barcelona.rent} target="_blank" rel="noopener noreferrer">{activeUi.rent} <ArrowUpRight size={14} /></a><a href={PROPERTY_LINKS.barcelona.sale} target="_blank" rel="noopener noreferrer">{activeUi.options} <ArrowUpRight size={14} /></a></div>
      {cookies && <div className="cookie"><div><strong>{activeUi.privacy}</strong><p>{activeUi.cookies}</p></div><button onClick={() => setCookies(false)} aria-label="Aceptar cookies"><Check size={17} /></button></div>}
    </main>
  )
}

function PropertyCard({ data, href, image, select }: { data: readonly [string, string, string]; href?: string; image: string; select: string }) { return <article className="property-card" style={{ backgroundImage: `linear-gradient(0deg, rgba(13,40,33,.9), rgba(13,40,33,.02) 80%), url(${image})` }}><div><span>{data[0]}</span><h3>{data[1]}</h3><p>{data[2]}</p>{href ? <ExternalLink href={href}>{select}</ExternalLink> : <button className="text-link light">{select} <ArrowUpRight size={16} /></button>}</div></article> }
function Service({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <article className="service"><div className="service-icon">{icon}</div><h3>{title}</h3><p>{text}</p></article> }
